### ISSUE TITLE
Applicants page 404s

### ISSUE THREAD

**Issue by Bforsyth1234** [cmaxw/coronadevjobs#2]
Expected: The applicants page to load.
Actual: The applicants page 404s
![Screen Shot 2020-04-01 at 11 45 48 AM](https://user-images.githubusercontent.com/4528782/78157740-586b1b80-740e-11ea-8082-3a644e24b7ee.png)

**Comment by cmaxw** [comment]
I dropped a quick and dirty fix here. Links to applicatnts goes to /news for now. I'm gonna dive in later and figure out the routing.
